package handlers

import "errors"

var (
	ErrUnauthorized            = errors.New("unauthorized")
	ErrMissingCredentials      = errors.New("missing username or password")
	ErrInvalidCredentials      = errors.New("invalid username or password")
	ErrPasswordFieldsRequired  = errors.New("current_password and new_password are required")
	ErrIncorrectPassword       = errors.New("current password is incorrect")
	ErrInvalidLanguage         = errors.New("invalid language: must be 'system', 'en', or 'de'")
	ErrEmptyNote               = errors.New("empty note")
	ErrMissingNoteID           = errors.New("missing note ID")
	ErrInvalidNoteIDFormat     = errors.New("invalid note ID format")
	ErrNotOwner                = errors.New("not owner")
	ErrCannotShareWithSelf     = errors.New("cannot share with self")
	ErrEmptyUsername           = errors.New("empty username")
	ErrEmptyNoteIDsList        = errors.New("empty note IDs list")
	ErrInvalidRole             = errors.New("invalid role: must be 'user' or 'admin'")
	ErrUsernameMinLength       = errors.New("username must be at least 2 characters")
	ErrUsernameMaxLength       = errors.New("username must be less than 30 characters")
	ErrUsernameInvalidChars    = errors.New("username can only contain letters, numbers, underscores, and hyphens")
	ErrUsernameInvalidStartEnd = errors.New("username cannot start or end with underscore or hyphen")
	ErrPasswordTooShort        = errors.New("password must be at least 4 characters")
	ErrInvalidZipFile          = errors.New("invalid zip file")
	ErrInvalidJSONFile         = errors.New("invalid JSON file")
	ErrEmptyNoteContent        = errors.New("note has no title, content, or list items")
	ErrFailedToParseForm       = errors.New("failed to parse form")
	ErrMissingFile             = errors.New("missing file")
)
