-- Fold users.username to lower case.
--
-- Usernames used to allow [a-zA-Z0-9_-] and the UNIQUE index on users.username
-- compares raw bytes, so "Ben" and "ben" were two separate accounts on both
-- backends and someone who registered as "Ben" could not sign in as "ben".
-- Validation now rejects upper case (server/internal/handlers/validation.go),
-- which makes the existing UNIQUE index case-insensitive in effect without an
-- expression index or a collation change: a username that differs only by case
-- can no longer be stored at all. This migration brings existing rows in line.
--
-- PostgreSQL's LOWER() is locale-aware where SQLite's folds ASCII A-Z only, but
-- the pre-existing username character set was [a-zA-Z0-9_-] — all ASCII — so the
-- two agree on every value that can be stored here. This is the same statement
-- as the SQLite counterpart and needs none of the COLLATE "C" pinning that
-- label names require (see internal/database/dialect.labelNameFold).
--
-- If two accounts fold to the same username this UPDATE hits the UNIQUE index
-- and the migration aborts, leaving both accounts intact. That is deliberate:
-- picking a winner is an operator decision, not a migration's. Startup runs
-- checkUsernameCollisions (server/internal/database/preflight.go) beforehand so
-- the failure names the accounts involved.
UPDATE users SET username = LOWER(username) WHERE username <> LOWER(username);
