import { useCallback } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useSQLiteContext } from 'expo-sqlite';
import type { SQLiteDatabase } from 'expo-sqlite';
import axios from 'axios';
import type { CreateNoteRequest, Note } from '@jot/shared';
import {
  getDeadLetteredOperations,
  deleteDeadLetter,
  deadLetterAffectedNoteIds,
  type DeadLetteredOperation,
} from '../db/syncQueue';
import {
  getLocalNote,
  saveNote,
  clearNoteSyncFailed,
  permanentDeleteLocalNote,
  markLocalNoteDeleted,
} from '../db/noteQueries';
import { reassignPendingImageUploads } from '../db/imageUploadQueue';
import { getNote } from '../api/notes';
import { useCreateNote } from './useNotes';
import { useOfflineContext } from '../store/OfflineContext';
import {
  deadLettersQueryKey,
  noteLocalQueryScopeKey,
  notesLocalQueryScopeKey,
} from './queryKeys';

/**
 * Build a fresh-note creation request from a note's preserved local content, so
 * "Keep my version" can fork the rejected change into a brand-new note that
 * carries no lost bytes (#493). A new note id is generated by the create path,
 * so the fork is independent of the original (possibly deleted/unshared) target.
 */
export function buildCreateRequestFromNote(note: Note): CreateNoteRequest {
  const labels = note.labels.map((l) => l.name);
  if (note.note_type === 'list') {
    return {
      note_type: 'list',
      title: note.title,
      color: note.color,
      labels,
      items: (note.items ?? []).map((item, index) => ({
        text: item.text,
        position: index,
        completed: item.completed,
        // The bulk-create endpoint reconstructs parent_id from indent_level
        // (0 = top-level, 1 = nested under the nearest preceding top-level item).
        indent_level: item.parent_id ? 1 : 0,
      })),
    };
  }
  return {
    note_type: 'text',
    content: note.content,
    color: note.color,
    labels,
  };
}

/** Whether a status means the original note is gone for this user (deleted/unshared). */
function isGoneStatus(status: number | undefined): boolean {
  return status === 403 || status === 404 || status === 410;
}

/**
 * Drop the local change and dead-letter row for a resolved failure, then
 * reconcile with the server so the note reflects authoritative state (#493). A
 * dead-lettered create never reached the server, so accepting server state means
 * removing the orphan local note; otherwise we clear the failed flag (lifting the
 * overwrite gate) and pull the server's version (tombstoning it locally if it's
 * gone for this user). Shared by both Discard and the tail of Keep-my-version.
 */
export async function reconcileDiscard(db: SQLiteDatabase, dl: DeadLetteredOperation): Promise<void> {
  if (dl.note_id) {
    if (dl.operation === 'create') {
      await permanentDeleteLocalNote(db, dl.note_id);
    } else {
      await clearNoteSyncFailed(db, dl.note_id);
      try {
        const serverNote = await getNote(dl.note_id);
        await saveNote(db, serverNote);
      } catch (err) {
        const status = axios.isAxiosError(err) ? err.response?.status : undefined;
        if (isGoneStatus(status)) {
          await markLocalNoteDeleted(db, dl.note_id);
        }
        // Offline or transient: the failed flag is already cleared, so a later
        // background fetch reconciles the note normally.
      }
    }
  } else {
    // A multi-note op (e.g. reorder) records its dead_letter row with note_id
    // NULL, but each affected note was still flagged sync_state='failed' when it
    // dead-lettered (#492). Clear every one of those flags here so resolving the
    // review banner also dismisses the per-note "didn't sync" badges — otherwise
    // they'd stay stuck until an unrelated successful write happened to touch
    // each note. Ops with no note at all (e.g. updateSettings) yield an empty
    // list, so this is a no-op for them.
    for (const noteId of deadLetterAffectedNoteIds(dl)) {
      await clearNoteSyncFailed(db, noteId);
    }
  }

  // Remove the dead-letter row last — only after the local reconciliation above
  // has completed — so a failure mid-reconciliation leaves the record intact and
  // the resolution can be retried instead of orphaning a still-failed note.
  await deleteDeadLetter(db, dl.id);
}

/**
 * Fork the preserved local content into a brand-new note via `createNote`, then
 * accept server state for the original (#493). The fork happens first and the
 * original is dropped only on success, so a failure here can never lose bytes.
 *
 * A dead-lettered `create` means the original note never reached the server,
 * so an image captured for it before the failure surfaced is still sitting in
 * the offline upload queue against the abandoned note id (drainImageUploadQueue
 * skips uploading it there, per issue #834). Reassign any such rows to the
 * fork before `reconcileDiscard` deletes the original and cascades them away.
 */
export async function keepThenDiscard(
  db: SQLiteDatabase,
  dl: DeadLetteredOperation,
  createNote: (req: CreateNoteRequest) => Promise<Note>,
): Promise<void> {
  if (dl.note_id) {
    const note = await getLocalNote(db, dl.note_id);
    if (note) {
      const forked = await createNote(buildCreateRequestFromNote(note));
      // Only a dead-lettered `create` makes reconcileDiscard below delete the
      // original note (an `update`/other failure keeps it and just clears the
      // failed flag) — reassign queued uploads only in that case, or this
      // would wrongly strip them from a note that isn't going anywhere.
      if (dl.operation === 'create') {
        await reassignPendingImageUploads(db, dl.note_id, forked.id);
      }
    }
  }
  await reconcileDiscard(db, dl);
}

/**
 * Surfaces preserved dead-lettered ops (#492) and the two MVP resolution actions
 * (#493):
 *   - keepMyVersion: fork the preserved local content into a new note, then
 *     accept server state for the original — no typed bytes are lost.
 *   - discard: accept server state and drop the local change + dead-letter row.
 *
 * Both clear the affected note's failed flag and refresh the badge/banner state.
 */
export function useSyncFailures() {
  const db = useSQLiteContext();
  const queryClient = useQueryClient();
  const createNote = useCreateNote();
  const { refreshSyncFailures } = useOfflineContext();

  const query = useQuery<DeadLetteredOperation[]>({
    queryKey: deadLettersQueryKey(),
    queryFn: () => getDeadLetteredOperations(db),
    staleTime: Infinity,
    gcTime: Infinity,
  });

  const afterResolve = useCallback(() => {
    queryClient.invalidateQueries({ queryKey: deadLettersQueryKey() });
    queryClient.invalidateQueries({ queryKey: notesLocalQueryScopeKey() });
    queryClient.invalidateQueries({ queryKey: noteLocalQueryScopeKey() });
    refreshSyncFailures();
  }, [queryClient, refreshSyncFailures]);

  const createNoteMutate = createNote.mutateAsync;

  const keepMyVersion = useCallback(async (dl: DeadLetteredOperation) => {
    await keepThenDiscard(db, dl, createNoteMutate);
    afterResolve();
  }, [db, createNoteMutate, afterResolve]);

  const discard = useCallback(async (dl: DeadLetteredOperation) => {
    await reconcileDiscard(db, dl);
    afterResolve();
  }, [db, afterResolve]);

  return {
    deadLetters: query.data ?? [],
    isLoading: query.isLoading,
    isError: query.isError,
    refetch: query.refetch,
    keepMyVersion,
    discard,
  };
}

/**
 * Map a dead-lettered op to a human-readable cause i18n key, so the review list
 * explains *why* a change couldn't be saved (#493). Status is the primary
 * signal; the operation refines the create-orphan wording.
 */
export function syncFailureCauseKey(dl: DeadLetteredOperation): string {
  switch (dl.status) {
    case 403:
      return 'syncFailures.causeUnshared';
    case 404:
    case 410:
      return 'syncFailures.causeDeleted';
    case 400:
    case 422:
      return 'syncFailures.causeInvalid';
    default:
      return 'syncFailures.causeUnknown';
  }
}
